In [3]:
import numpy as np

In [53]:
# Numpy is a general-purpose array-processing package.
# It provides a high-performance multidimensional array object, and tools for working with these arrays.
# It is the fundamental package for scientific computing with Python.
# Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data.


# ARRAY - storing data in rows and column format is refer to array

In [54]:
# There are 6 general mechanisms for creating arrays:👇

# 1. Conversion from other Python structures (i.e. lists and tuples)

In [55]:
# use double bracket to convert list to array --> [[lists]]
listarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [56]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
listarr.dtype

dtype('int32')

In [58]:
listarr.shape # 3 rows and 3 columns

(3, 3)

In [59]:
listarr.size # total items

9

In [60]:
listarr[0,2] # to retrive data from array --> oth(1st) row and 2nd(3rd) column

3

In [61]:
marks = [1,2,3,4,5,6,7,8]
# converting list to array

np.array(marks).reshape(2,4) # reshape gives rows and colums to your single dimension arrays

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# 2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [62]:
# creating arrays via NUMPY FUNCTIONS
# creating array with arrange function of numpy --> arange works as a range function but creates array as well

a = np.arange(15) # -> single dimension
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
b = np.arange(15,30).reshape(3,5) # --> multi dimensiom
b

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [64]:
# CUSTOM RANGE

rangE = np.arange(0,2,0.3) # range from 0 to 2 but at differnce of 0.3 or gaps of 0.3
rangE

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [65]:
b.size
b.shape

(3, 5)

In [66]:
a.ndim # --> dimensions

1

In [67]:
# creating array via zeros

zer0 = np.zeros((2,5)) # --> by default zero function already have zeros , we jus need to specify number of rows and colums 
zer0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [68]:
# arrays of ones
one_S = np.ones((10,10))
one_S

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [69]:
lspace = np.linspace(1,5,12) #  between 1 and 5 , it will give equally lineary spaced 12 elements 
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [70]:
emp = np.empty((4,6)) # it will give an empty array with random values after which you can assign any values to this array
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34609111e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11261027e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 7.56599128e-307,
        1.11260144e-306, 6.89812281e-307, 2.22522596e-306]])

In [71]:
# to make 2d array to 1d array use ravel function, for eg
abc = np.array([[1,2,3,4,5],[6,7,8,9,10]])
abc

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [72]:
# inorder to make abc back to 1d array

abc.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# before moving forward let's see some -> ***Basic Operations***

In [73]:
arr = np.array([[10,11,12],[13,14,15],[18,19,20]])
arr


array([[10, 11, 12],
       [13, 14, 15],
       [18, 19, 20]])

In [74]:

# now if you want to have sum of axis 0 (all columns) and 1 (all rows)
arr.sum(axis = 0)
arr.sum(axis = 1)

array([33, 42, 57])

In [75]:
arr.T # T stands for transpose it will convert rows into columns and columns into rows

array([[10, 13, 18],
       [11, 14, 19],
       [12, 15, 20]])

In [76]:
arr.flat # it makes the array itreable like you can access elements using for loop

In [77]:
for item in arr.flat:
    print(item)

10
11
12
13
14
15
18
19
20


In [78]:
arr.nbytes # tells how much space your array is consuming in bytes

36

In [79]:
z = np.array([[22,23,28],[28,19,21],[17,26,29]])
z

array([[22, 23, 28],
       [28, 19, 21],
       [17, 26, 29]])

In [80]:
# now if you want to work with the indexes of the array , here are few functions

z.argmax() # shows the element at maximum index

8

In [81]:
z.argmin() # shows the element at minimum index

6

In [82]:
z.argsort() # sorted values as per index in ascend order

array([[0, 1, 2],
       [1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [83]:
# same thing can be done as per the axis like 👇🏻👇🏻
z.argmin(axis = 0)

array([2, 1, 1], dtype=int64)

In [84]:
z.argsort(axis = 0)

array([[2, 1, 1],
       [0, 0, 0],
       [1, 2, 2]], dtype=int64)

In [85]:
# basic operations

listarr = np.array([[1,2,3],[4,5,6],[7,8,9]])
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
z

array([[22, 23, 28],
       [28, 19, 21],
       [17, 26, 29]])

In [87]:
listarr + z

array([[23, 25, 31],
       [32, 24, 27],
       [24, 34, 38]])

In [88]:
listarr - z
listarr*z

array([[ 22,  46,  84],
       [112,  95, 126],
       [119, 208, 261]])

In [89]:
listarr @ z # matrix product 

array([[129, 139, 157],
       [330, 343, 391],
       [531, 547, 625]])

In [90]:
listarr.min()
listarr.max()
listarr.sum()

45

In [91]:
# to find a particular element in arrray 
#z > 20 refers elements in array z greater than 20
np.where(z>20)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 1, 2], dtype=int64))

In [92]:
# numpy.random.random () is one of the function for doing random sampling in numpy. 
# It returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0)

p = np.random.random((3,4))
p

array([[0.10404357, 0.95107377, 0.57939395, 0.44583814],
       [0.77237929, 0.17457353, 0.41079516, 0.94270268],
       [0.64818559, 0.66538476, 0.24629445, 0.39535044]])

In [93]:
q = np.ones((3,4))
q

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [94]:
p =p*3
q =q*3

In [95]:
p

array([[0.31213072, 2.85322132, 1.73818186, 1.33751443],
       [2.31713787, 0.5237206 , 1.23238548, 2.82810803],
       [1.94455677, 1.99615428, 0.73888335, 1.18605132]])

In [96]:
q

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [97]:
p*q

array([[0.93639216, 8.55966396, 5.21454558, 4.01254329],
       [6.95141362, 1.5711618 , 3.69715645, 8.4843241 ],
       [5.83367031, 5.98846284, 2.21665004, 3.55815396]])

In [98]:
# https://docs.scipy.org/doc/numpy-1.14.0/index.html 

#  you can get here the attributes and methods used in numpy

# numpy maths (digi_p) 👇🏻

In [8]:


x = np.array([[1,2],[3,4]])
y = np.array([[6,7],[8,9]])


In [7]:
print(x+y)

[[ 7  9]
 [11 13]]


In [6]:
x-y

array([[-5, -5],
       [-5, -5]])

In [9]:
z = x*y
print(z)

[[ 6 14]
 [24 36]]


In [12]:
c = np.random.randint(0,100,(5,7))
c

array([[79, 19, 77, 38, 57, 70, 28],
       [25,  9, 51, 10, 74, 60, 91],
       [58, 86, 47, 11, 33, 55,  1],
       [66, 32, 35, 56, 28, 77, 12],
       [36, 48, 35, 81, 74, 52,  8]])

In [14]:
print(c.sum() ,' --> all values')
print(c.sum(axis = 0)  , '--> column wise')
print(c.sum (axis = 1) , '--> row wise')

1619  --> all values
[264 194 245 196 266 314 140] --> column wise
[368 320 291 306 334] --> row wise


In [15]:
print(c.mean() ,' --> all values')
print(c.mean(axis = 0)  , '--> column wise')
print(c.mean (axis = 1) , '--> row wise')

46.25714285714286  --> all values
[52.8 38.8 49.  39.2 53.2 62.8 28. ] --> column wise
[52.57142857 45.71428571 41.57142857 43.71428571 47.71428571] --> row wise


# similarly you can get for ***std(), min(),max()***

In [19]:
# np. shows direct function from numpy
print(np.sin(c))


[[-0.44411267  0.14987721  0.99952016  0.29636858  0.43616476  0.77389068
   0.27090579]
 [-0.13235175  0.41211849  0.67022918 -0.54402111 -0.98514626 -0.30481062
   0.10598751]
 [ 0.99287265 -0.92345845  0.12357312 -0.99999021  0.99991186 -0.99975517
   0.84147098]
 [-0.02655115  0.55142668 -0.42818267 -0.521551    0.27090579  0.99952016
  -0.53657292]
 [-0.99177885 -0.76825466 -0.42818267 -0.62988799 -0.98514626  0.98662759
   0.98935825]]


In [18]:
print(np.cos(c))


[[-0.89597095  0.98870462 -0.03097503  0.95507364  0.89986683  0.6333192
  -0.96260587]
 [ 0.99120281 -0.91113026  0.7421542  -0.83907153  0.17171734 -0.95241298
  -0.99436746]
 [ 0.11918014 -0.38369844 -0.99233547  0.0044257  -0.01327675  0.02212676
   0.54030231]
 [-0.99964746  0.83422336 -0.90369221  0.85322011 -0.96260587 -0.03097503
   0.84385396]
 [-0.12796369 -0.64014434 -0.90369221  0.77668598  0.17171734 -0.16299078
  -0.14550003]]


In [21]:
x = np.random.randint(0,100,(8,15))
x

array([[50, 31, 37,  4, 40, 45, 44, 70, 65, 33, 84, 13, 49, 59,  0],
       [65, 29, 38, 64, 90, 72, 54, 21, 27, 92, 32, 74, 85, 91, 59],
       [76, 98, 30, 17,  7, 70, 21, 37,  7, 43, 26, 85, 70, 15, 55],
       [21, 87, 46, 56, 40, 90,  6, 61, 38, 67, 45, 47, 78, 87, 22],
       [75, 39, 13, 41, 15, 65, 91, 64, 52, 95,  5, 81,  9, 67, 74],
       [10, 25, 60, 63, 14, 52, 71, 26, 26, 99, 52, 34, 55, 11, 19],
       [ 4, 63, 58, 97, 96, 78, 86, 44, 72, 74, 80, 93, 10, 48, 66],
       [46,  9, 95, 52, 91, 68,  8,  0, 17, 82, 24,  6,  1, 12, 83]])

# boolean filtering

In [27]:
x > 50
#  just displays boolean matrix

array([[False, False, False, False, False, False, False,  True,  True,
        False,  True, False, False,  True, False],
       [ True, False, False,  True,  True,  True,  True, False, False,
         True, False,  True,  True,  True,  True],
       [ True,  True, False, False, False,  True, False, False, False,
        False, False,  True,  True, False,  True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True, False, False,  True,  True, False],
       [ True, False, False, False, False,  True,  True,  True,  True,
         True, False,  True, False,  True,  True],
       [False, False,  True,  True, False,  True,  True, False, False,
         True,  True, False,  True, False, False],
       [False,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True, False, False,  True],
       [False, False,  True,  True,  True,  True, False, False, False,
         True, False, False, False, False,  True]])

In [28]:
x[x>50] # --> inside square bracket you can not only access elements but also extract elements based on  condition

array([70, 65, 84, 59, 65, 64, 90, 72, 54, 92, 74, 85, 91, 59, 76, 98, 70,
       85, 70, 55, 87, 56, 90, 61, 67, 78, 87, 75, 65, 91, 64, 52, 95, 81,
       67, 74, 60, 63, 52, 71, 99, 52, 55, 63, 58, 97, 96, 78, 86, 72, 74,
       80, 93, 66, 95, 52, 91, 68, 82, 83])

In [29]:
f1 = x > 20
f2 = x < 50

In [30]:
x[f1 & f2]

array([31, 37, 40, 45, 44, 33, 49, 29, 38, 21, 27, 32, 30, 21, 37, 43, 26,
       21, 46, 40, 38, 45, 47, 22, 39, 41, 25, 26, 26, 34, 44, 48, 46, 24])