In [1]:
import numpy as np

In [ ]:
# Numpy is a general-purpose array-processing package.
# It provides a high-performance multidimensional array object, and tools for working with these arrays.
# It is the fundamental package for scientific computing with Python.
# Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data.


# ARRAY - storing data in rows and column format is refer to array

In [ ]:
# There are 6 general mechanisms for creating arrays:👇

# 1. Conversion from other Python structures (i.e. lists and tuples)

In [5]:
# use double bracket to convert list to array --> [[lists]]
listarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
listarr.dtype

dtype('int32')

In [8]:
listarr.shape # 3 rows and 3 columns

(3, 3)

In [9]:
listarr.size # total items

9

In [11]:
listarr[0,2] # to retrive data from array --> oth(1st) row and 2nd(3rd) column

3

In [19]:
marks = [1,2,3,4,5,6,7,8]
# converting list to array

np.array(marks).reshape(2,4) # reshape gives rows and colums to your single dimension arrays

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# 2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [13]:
# creating arrays via NUMPY FUNCTIONS
# creating array with arrange function of numpy --> arange works as a range function but creates array as well

a = np.arange(15) # -> single dimension
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
b = np.arange(15,30).reshape(3,5) # --> multi dimensiom
b

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [26]:
# CUSTOM RANGE

rangE = np.arange(0,2,0.3) # range from 0 to 2 but at differnce of 0.3 or gaps of 0.3
rangE

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [17]:
b.size
b.shape

(3, 5)

In [18]:
a.ndim # --> dimensions

1

In [20]:
# creating array via zeros

zer0 = np.zeros((2,5)) # --> by default zero function already have zeros , we jus need to specify number of rows and colums 
zer0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
# arrays of ones
one_S = np.ones((10,10))
one_S

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])